### ISSUE TITLE
Why do I need to enter my Password?

### ISSUE THREAD

**Issue by SuperSandro2000** [Ne3tCode/SteamItemDropIdler#1]
In Kokole's version there was no need to enter my password. Is there a reason why I need to? Could you make it possible that I don't need to?

**Comment by Ne3tCode** [comment]
> Why do I need to enter my Password?

2 possible options:
1) I want to steal your account and inventory.
2) Your account name and password used to log in to Steam account.
(j/k :smile:)

Since version 2.0 Steam Item Drop Idler is standalone application, and there is still no "remember password" option to auto login, but it is planned for future version.
